### ISSUE TITLE
create API project directory

### ISSUE THREAD

**Issue by inidaname** [mainheartng/backend-api#5]
Following the issue mainheartng/organization#5, when the linked pr mainheartng/organization#6 is merge create a project directory for API

**Comment by hallydon** [comment]
Two questions 
1) suggest a name for the directory for the API.
2) Can i creat the directory from Git bash then push?

**Comment by hallydon** [comment]
Two questions 
1) suggest a name for the directory for the API.
2) Can i creat the directory from Git bash then push?

**Comment by hallydon** [comment]
Two questions 
1) suggest a name for the directory for the API.
2) Can i creat the directory from Git bash then push?

**Comment by inidaname** [comment]
> Two questions 
> 1) suggest a name for the directory for the API.
> 2) Can i creat the directory from Git bash then push?

For the base directory that should already exist from the git project you clone. For other directories follow the list mentioned in mainheartng/organization#6 PR.

Note: this depends on the PR MainHeartng/organization#6

**Comment by inidaname** [comment]
@hallydon following successfully merged of mainheartng/organization#6 you can now go ahead to work on this
